# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "pebkac"
description: > # this means to ignore newlines until "email:"
   A virtualisation engineers venture into all things public cloud!

timezone: Australia/Brisbane #	+10:00	+10:00

email: info@leet.cloud
#blog logo
logo: "/assets/images/pebcak-logo-300x300.png"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/cover-no-earth.png"

name: 'Alex Simpson'
author: 'Alex Simpson'
author_image: "/assets/images/author-grey.png"

paginate:	5

url: "http://blog.leet.cloud" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@vendablefall'

#fill in disqus shortname to use disqus
disqus: blog-leet-cloud

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/vendablefall
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	github
    url:	https://github.com/vendablefall
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

  - icon: linkedin
    url:  https://www.linkedin.com/in/alexander-simpson-35716189/
    desc: Connect with me on Linkedin
    share_url: 
    share_title: ?t=
    share_link: "&amp;u="
